### ISSUE TITLE
Turbolinks causes wrong height on all page visits except first.

### ISSUE THREAD

**Issue by szyablitsky** [andreypopp/react-textarea-autosize#101]
I'm using this component on site with [turbolinks](https://github.com/turbolinks/turbolinks).
When I visit page with `textarea-autosize` component for the first time I can see how it sets the right size for control. But if I navigate on other page and return back to the page with `textarea-autosize` component then the height is set to 2px and does not change with user input.

**Comment by jdalton** [comment]
Turbolinks does a lot of things under the hood that may cause issues with third party code. This feels more like a Turbolinks concern.

**Comment by wsmd** [comment]
Having same issue here. I can confirm that is caused by Turbolinks.

For those on rails apps, try this in your browser console:
```js
Turbolinks.visit(window.location)
```

 All `<Textarea />`s' heights will be set to `0px` (at least for me).

![screen shot 2016-11-16 at 2 07 03 pm](https://cloud.githubusercontent.com/assets/2100222/20361644/5777b50e-ac06-11e6-8f22-ebb4486b710d.png)

A hard refresh will result in accurate heights

![screen shot 2016-11-16 at 2 07 44 pm](https://cloud.githubusercontent.com/assets/2100222/20361634/4f34966e-ac06-11e6-993c-677d7cb5e46d.png)

If anyone has found a solution for this, please hesitate to share the knowledge :)

**Comment by wsmd** [comment]
Having same issue here. I can confirm that is caused by Turbolinks.

For those on rails apps, try this in your browser console:
```js
Turbolinks.visit(window.location)
```

 All `<Textarea />`s' heights will be set to `0px` (at least for me).

![screen shot 2016-11-16 at 2 07 03 pm](https://cloud.githubusercontent.com/assets/2100222/20361644/5777b50e-ac06-11e6-8f22-ebb4486b710d.png)

A hard refresh will result in accurate heights

![screen shot 2016-11-16 at 2 07 44 pm](https://cloud.githubusercontent.com/assets/2100222/20361634/4f34966e-ac06-11e6-993c-677d7cb5e46d.png)

If anyone has found a solution for this, please don't hesitate to share the knowledge :)

**Comment by wsmd** [comment]
**Update**

I also tried to do the following in hope of letting `<Textarea />` calculate the right height after the page has mounted.

```jsx
import React, { Component } from 'react';
import Textarea from 'react-textarea-autosize';

class TextareaWrapper extends Component {
  constructor(props) {
    super(props);
    this.state = { showText: false };
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({ showText: true });
    }, 1000)
  }

  render() {
    return this.state.showText && (
      <Textarea {/* passing some props here */} />
    );
  }
}
```

This will mount `<Textarea />` a second after the wrapper component has mounted when visiting a page via Turbolinks. Unfortunately that didn't do the trick. Height of rendered `<textarea />` is still `0px`.

**Comment by szyablitsky** [comment]
Now we are using https://github.com/buildo/react-autosize-textarea
That component does not have this issue
