### ISSUE TITLE
Doesn't work with React.addons.LinkedStateMixin

### ISSUE THREAD

**Issue by glifchits** [andreypopp/react-textarea-autosize#12]
I get `Uncaught Error: Invariant Violation: Cannot provide a valueLink and a value or onChange event. If you want to use value or onChange, you probably don't want to use valueLink.` Makes sense, but it would be nice if this worked with the LinkedStateMixin as a "drop-in replacement".

**Comment by KyleAMathews** [comment]
I don't see a way to support `valueLink` actually as we use `onChange` events to recalculate the textarea size... which is disappointing. It's too bad React thinks this an `error` as what we're doing is a perfectly valid use case for having both an `onChange` and `valueLink.

@glifchits — perhaps file a issue against React.

**Comment by glifchits** [comment]
Fortunately I was easily able to work around this by adding my own `onChange` to the Autosize Textarea and writing a "value link". Would it be valuable to write a linked state mixin that is to be included in this library?

**Comment by KyleAMathews** [comment]
Including it seems a bit out-of-scope but definitely post the code either as a new NPM module or just paste the code in here as an example.

**Comment by eugene1g** [comment]
@KyleAMathews Thanks for the component. FYI I reconciled it with ValueLink by making two small adjustments - 

If ValueLink is passed, then extract the value from it and then put it aside so that it is not activated automatically and hence does not complain about the onChange handler
```
    render: function () {
        var props = objectAssign({}, this.props, {
            onChange: this.onChange,
            style:    objectAssign({}, this.props.style, {overflow: 'hidden'})
        });

       
        //ValueLink addition starts here
        if(props.valueLink)
        {
            props.defaultValue = props.valueLink.value;
            this.valueLink = props.valueLink;
            delete props.valueLink;
        }
        // end of addition
        return React.DOM.textarea(props, this.props.children);
    }
```
Then during the onChange even, check if the component is used with a ValueLink and if so just trigger it with the new value so that ValueLink runs as per usual
```
    onChange: function(e) {
        if (this.props.onChange) {
            this.props.onChange(e);
        }
        //ValueLink addition starts here
        if(this.valueLink)
        {
            this.valueLink.requestChange(e.target.value);
        }
        // end of addition
        
        if (this.props.value === undefined) {
            // controlled mode
            this.recalculateSize();
        }
    },

**Comment by KyleAMathews** [comment]
Oh this looks great! I guess I spoke too soon when I said we couldn't support `valueLink` :)

Could you put together a PR that we can do a proper review of?

**Comment by eugene1g** [comment]
Sure - just opened  #17

**Comment by sstern6** [comment]
Thanks for the post, this really help me solve a 2-way data binding issue.  I am very new to React and this gave me some guidance.

What I was trying to do is auto complete the dashes for a proper phone number on user input.  If anyone is interested, onChange I bound to a handle click function that would change state to e.target.value, and if the number was of a certain logic would autofill the correct format for the phone number.  On the DOM side I set value to value={this.state.userInput} because I kept getting the error @glifchits  got by using valueLink.
