### ISSUE TITLE
IE11 requestAnimationFrame + eval source maps problem

### ISSUE THREAD

**Issue by hjylewis** [andreypopp/react-textarea-autosize#185]
Is there a reason we only do the bind when `process.env.NODE_ENV !== 'development'`?
 https://github.com/andreypopp/react-textarea-autosize/blob/master/src/index.js#L18

**Comment by Andarist** [comment]
It's only necessary for IE11 when using eval source maps, not binding is more idiomatic usage and saves few bytes. Is there any problem with this approach?

**Comment by hjylewis** [comment]
No, that makes sense. I only wonder if there's a case where someone is working with a code base that uses a different `NODE_ENV` like `dev`.

**Comment by Andarist** [comment]
He won't be able to use eval source maps in IE11 - I don't personally consider this much of a problem. `development`, `production` and `test` are somewhat standard strings for distinguishing the env, so if one shortens it to `dev` - well, he should probably migrate to more common `development`. Not because this library uses it, but because many others do.

**Comment by hjylewis** [comment]
Makes sense to me. Thanks.
