### ISSUE TITLE
Incorrect initial height when font-size isn't the initial value

### ISSUE THREAD

**Issue by angelolucas** [andreypopp/react-textarea-autosize#218]
I'd like to create `textarea`s with two different `font-size`.
The problem is fixed after typing something.

Apply `_resizeComponent()` with `setTimeout` inside `componentDidMount` fixes de problem but I don't now if this is the best solution:

```
_proto.componentDidMount = function componentDidMount() {
  [...]
  setTimeout(() => this._resizeComponent())
  [...]
}
```

**Comment by angelolucas** [comment]
Apply `_resizeComponent()` with `setTimeout inside` inside `componentDidMount` fixes de problem but I don't now if this is the best solution:

```
_proto.componentDidMount = function componentDidMount() {
  [...]
  setTimeout(() => this._resizeComponent())
  [...]
}
```

**Comment by Andarist** [comment]
Could u create a small repository illustrating the issue?

**Comment by angelolucas** [comment]
@Andarist, here:
https://angelolucas.github.io/react-textarea-autosize-issue
https://github.com/angelolucas/react-textarea-autosize-issue

Actually, the problem happens because I'm using CSS-in-JS (aphrodite). 
With normal CSS there's no problem.

**Comment by Andarist** [comment]
That is because aphrodite does not inject styles immediately but rather it uses some kind of scheduling - https://github.com/Khan/aphrodite/blob/62ee2f0a39f10be75322dc0f77d1346e9731ffbf/src/inject.js#L163-L178

We cannot work around this in here, the timing of the injection is nondeterministic - you have to find hacky way to solve this for your case. Maybe you can call `flushToStyleTag` in some react hook before Textarea's `componentDidMount` gets called? You probably would have to do smth like
```js
someHookInSomeComponent() {
  css(styles.bigFont)
  flushToStyleTag()
}
```
because `css` call is actually queuing the style insertion.

**Comment by angelolucas** [comment]
Yes, I agree. This is not a issue with this component. At first I thought it was.

I decided to put the inline font size: `<Textarea style={{ fontSize: '32px' }} ... />`

Thanks so much for your help.

**Comment by Andarist** [comment]
No problem, going to close the issue as solved :)
