### ISSUE TITLE
Number of rows shown is wrong in Firefox

### ISSUE THREAD

**Issue by necolas** [andreypopp/react-textarea-autosize#55]
This difference only surfaces at unrealistically small font sizes (used in a test case).

 `maxRows={3}` and `style={{ lineHeight: 1, fontSize: 10, border: 0, boxSizing: 'border-box' }}`

In Chrome the textarea shows 3 rows, height of `33px`

In Firefox the textarea shows 4 rows, height of `39px`

**Comment by andreypopp** [comment]
Chrome has the same issue for me.

**Comment by comp615** [comment]
@andreypopp circling back on this. It seems changing the value is actually worse for Edge and doesn't fix the original problem. Edge claims that they (and firefox mobile) compute the height of an empty textarea as 0, and we should use 'x' to actually get the line height.

I did a little playing on my own, and indeed it seems regardless of '' vs 'x' in firefox, the issue @necolas mentions above still exists. Chrome correctly computes the single line height as 10, where Firefox pegs it at 13. This causes both the initial (min) height to be wrong, as well as the cap height (39 instead of 30).

For now, I'd say we should revert #58 and then reopen this ticket to figure out why that is. See also #74 #77.

**Comment by jdalton** [comment]
> For now, I'd say we should revert #58 and then reopen this ticket to figure out why that is. See also #74 #77.

Done! While an incorrect hight is a bummer for Firefox, this patch broke IE/Edge support for sites like Twitter which use `react-textarea-autosize`.

**Comment by jdalton** [comment]
Issue doesn't repro in FF 48.
