### ISSUE TITLE
Typing is garbled in IE11

### ISSUE THREAD

**Issue by insin** [andreypopp/react-textarea-autosize#99]
Typing "Typing a test message" (and messing it up the second time :smile_cat:) with react/react-dom@15.0.2 and react-textarea-autosize@4.0.1:

![react-textarea-autosize-ie11](https://cloud.githubusercontent.com/assets/226692/14979163/7736891c-1118-11e6-84e6-a5a5e0e58360.gif)

The event handler isn't doing anything asynchronous:

``` js
  handleTextChange(e) {
    this.setState({text: e.target.value})
  },
```

This only seems to happen when the component is controlled - working around it by using it without a `value` prop. as that suits my current use case.

**Comment by andreypopp** [comment]
Hm.. tried on a VM with IE11 downloaed from modern.ie:

![ie11-react-textarea-autosize](https://cloud.githubusercontent.com/assets/30594/14983856/54185f20-1148-11e6-92b9-3a3c9a2abb38.gif)

**Comment by insin** [comment]
Is the purpose of this line in `componentWillUpdate()` to resize the textarea when it's controlled and a new value is forced into it via a prop, rather than by using the textarea?

```js
this._onNextFrameActionId = onNextFrame(this._resizeComponent);
```

Commenting this out makes IE11 behave when typing normally - could it be a difference in how IE implements `requestAnimationFrame`?

**Comment by andreypopp** [comment]
Can you try code in `controlled` branch? I removed rAF call there and simplified code to allow only controlled usage (also removed support for `valueLink` pattern).

**Comment by insin** [comment]
Looks good to me in IE

![controlled-branch](https://cloud.githubusercontent.com/assets/226692/15041588/fd73f5c6-12b4-11e6-9079-6ea2dd3790a2.gif)

**Comment by andreypopp** [comment]
Ok, I'll wait for feedback on #100 a little bit and then release it (or not :-)).

**Comment by averyvery** [comment]
We also have users experiencing this issue, glad someone caught it!

**Comment by averyvery** [comment]
Any updates on this? Is it ready to merge?

**Comment by frontendphil** [comment]
I would also like to see that being merged / fixed :) I'll have to disable this feature now, because I cannot ship to customers otherwise.

**Comment by xylude** [comment]
I had this problem in an application, not with just this module, but regular text inputs too. React made a change in v15 to how the change event is handled in IE11 and below - my solution was just to change the 'onChange' event to 'onInput'. After that everything worked just fine.

**Comment by Andarist** [comment]
@andreypopp 
what did happen with `controlled` branch? I dont see it included in the `master` and it got deleted I think, is there a plan to release it? I had to fork the repo and merge `controlled` in the past so I can ship my app without this bug, but would like to eventually include the original lib instead of a fork

**Comment by andreypopp** [comment]
@Andarist see https://github.com/andreypopp/react-textarea-autosize/pull/100 also I've stepped down  as a maintainer of react-textarea-component so @jdalton makes the call here

**Comment by vinnymac** [comment]
I noticed that some [changes](https://github.com/facebook/react/pull/8020) were made in React for IE 11 in the latest release (v15.4.2).

We might want to recheck these IE 11 bugs given React has resolved issues of its own regarding textarea elements.

#125 may also be affected.

**Comment by Andarist** [comment]
I had problem with this too, after some PRs merged in and new release today Ive just tested it (manually ofc) on the computer with IE11 which was affected before bumping library version and the problem seems to be gone.

Other popped up, but aint sure if new. At least typing is not more garbled (for me). Going go to close this issue, but if anyone still suffers from this problem at the newest version of the library then please raise your voice, I will reopen and do my best to fix this.
